### PR TITLE
#935 Fix next page bug with a unit test validation

### LINKED ISSUE #935: Surat Quraysh not Downloading
Dears,
Stay blessed. Ameen,

I have installed the app from google play store, all working fine, Audios are downoading fine. But just some Surahs such that "Surat Quraysh" , "Surat l-Kafirun", "Surat Al-Qariah" and there are few more, won't download. Even though I click on play icon it does not start downloading. Please have a look on the screenshot and in this screenshot if I click on play icon it does not start downloading the audios. 

surat quraysh screenshot

I installed it in another android mobile and same issue.

Thanks in advance.

### PR DESCRIPTION
**Pull request by AhmedKamal**
- Fix the page index bug and remove unnecessary code
- Change the scope of MadaniDataSource for unit testing
- Add a simple unit test for this case

Fixes #935.

### CODE REVIEW

**Comment by AhmedKamal** [comment]
@ozbek Please check when you have time :)

File: app/src/test/java/com/quran/labs/androidquran/util/AudioUtilsTest.java [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+import com.quran.labs.androidquran.data.SuraAyah;
+import org.junit.Test;
+import org.mockito.InjectMocks;
+import org.mockito.Mockito;
+
+import static org.junit.Assert.assertTrue;
+import static org.mockito.Mockito.when;
+
+/**
+ * Created by akamal on 3/25/18.
```
Comment (ozbek) [inline app/src/test/java/com/quran/labs/androidquran/util/AudioUtilsTest.java]: I'd remove or otherwise put something helpful here :)

File: common/pageinfo/src/main/java/com/quran/data/page/provider/madani/MadaniDataSource.kt [hunk 2]
```diff
@@ -2,7 +2,7 @@ package com.quran.data.page.provider.madani
 
 import com.quran.data.source.QuranDataSource
 
-internal open class MadaniDataSource : QuranDataSource {
+open class MadaniDataSource : QuranDataSource {
```
Comment (ahmedre) [inline common/pageinfo/src/main/java/com/quran/data/page/provider/madani/MadaniDataSource.kt]: can you undo this change? since you're making a new one in the test and not mocking it, it should work.

File: app/src/test/java/com/quran/labs/androidquran/util/AudioUtilsTest.java [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+ */
+public class AudioUtilsTest {
+
+  @InjectMocks
+  QuranInfo quranInfoMock;
```
Comment (ahmedre) [inline app/src/test/java/com/quran/labs/androidquran/util/AudioUtilsTest.java]: inline into the method and remove `@InjectMocks`

**Comment by ahmedre** [comment]
jazakAllah khairan for making this fix!

File: common/pageinfo/src/main/java/com/quran/data/page/provider/madani/MadaniDataSource.kt (hunk 2 above)
Comment (AhmedKamal) [reply common/pageinfo/src/main/java/com/quran/data/page/provider/madani/MadaniDataSource.kt]: Changed, the reason I changed it at first place is to avoid this inspection warning
"Usage of kotlin internal declaration from different module"

The test still works after reverting back although.

**Comment by AhmedKamal** [comment]
I'm not able to pass the travis CI build. Not sure why is it failing.

**Comment by ahmedre** [comment]
sometimes Travis fails with the integration tests - i've restarted the build.

**Comment by ahmedre** [comment]
jazakAllah khairan!
