### PR TITLE
Fix bugs with recent pages

### LINKED ISSUE #725: bug with RecentPages
while developing, i noticed that sometimes, `onPageChanged` is called before `bind` is called in the `RecentPagePresenter` - consequently, this offsets the page by one and results in things being wrong.

### PR DESCRIPTION
**Pull request by ahmedre**
This patch fixes #725. It exposes an Observable that observes every time
onPageSelected is called on a ViewPager. RecentPagePresenter subscribes
to this and uses this information to know how to update its recent page
state.

### CODE REVIEW

File: app/src/main/java/com/quran/labs/androidquran/ui/PagerActivity.java [hunk 1]
```diff
@@ -493,8 +496,29 @@ public void onPageSelected(int position) {
     downloadReceiver.setListener(this);
   }
 
-  private void saveRecentPage(int page) {
-    recentPagePresenter.onPageChanged(page);
+  public Observable<Integer> getViewPagerObservable() {
```
Comment (ahmedre) [inline app/src/main/java/com/quran/labs/androidquran/ui/PagerActivity.java]: some "thinking out loud" thoughts:

i am thinking something like this should be used to also clean up other logic (our massive `onCreate` method in `PagerActivity` for example. thinking about splitting some of that logic into a `PagePresenter` of sorts, and that can also `getViewPagerObservable` and subscribe to it so as to handle changes there separately from here.

at that point, we can then decide to cache this Observable in a variable initialized in onCreate and calling `share` on it so we can have multiple observers to it (with only one `OnPageChangeListener`).

another thought:
should we split out presenters and some sort of "view presenters" - i.e. what's the right place for this method to live? it felt strange for this to be `getViewPager` instead and the work be done in the presenter.
